# Menus
menu:
    Home: /
    # Delete this row if you don't want categories in your header nav bar
    Categories:
    About: /about/index.html

# Customize
customize:
    logo:
        width: 90
        height: 90
        url: images/logo.png
    theme_color: '#de006f'
    highlight: androidstudio
    sidebar: left # sidebar position, options: left, right
    thumbnail: true # enable posts thumbnail, options: true, false
    favicon: css/images/favicon.png
    social_links: # for more icons, please see http://fontawesome.io/icons/#brand
        facebook: https://www.facebook.com/perfectacle
        github: https://github.com/perfectacle
        rss: /atom.xml

# Widgets
widgets:
    - category
    - archive
    - tagcloud
    - links

# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false

# Comment
comment:
    disqus: exobud # enter disqus shortname here
    facebook: true # enter true to enable

# Share
share: default # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
    lightgallery: true # options: true, false
    google_analytics: UA-87795455-1
    mathjax: true # options: true, false

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
    links:
        이전 블로그: http://perfectacle.blog.me/
        Mozilla MDN: https://developer.mozilla.org/en/
        w3schools: http://www.w3schools.com/
        Pro Git 2nd Edition: https://git-scm.com/book/ko/v2
        각종 언어 fiddle: https://fiddles.io/
        정규 표현식 테스트: http://regexr.com/
        알고리즘 사이트: http://tryhelloworld.co.kr/challenges?page=2